#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinclude
CFLAGS = -std=c++11 -fPIC
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -pthread -lrt

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -Wall -g -DNDEBUG
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/ipclib_d.so

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -Wall -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/ipclib.so

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/msg_queue.o $(OBJDIR_DEBUG)/src/posix_object.o $(OBJDIR_DEBUG)/src/posix_semaphore.o $(OBJDIR_DEBUG)/src/result.o $(OBJDIR_DEBUG)/src/shared_memory.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/msg_queue.o $(OBJDIR_RELEASE)/src/posix_object.o $(OBJDIR_RELEASE)/src/posix_semaphore.o $(OBJDIR_RELEASE)/src/result.o $(OBJDIR_RELEASE)/src/shared_memory.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) -shared $(LIBDIR_DEBUG) $(OBJ_DEBUG)  -o $(OUT_DEBUG) $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/msg_queue.o: src/msg_queue.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/msg_queue.cpp -o $(OBJDIR_DEBUG)/src/msg_queue.o

$(OBJDIR_DEBUG)/src/posix_object.o: src/posix_object.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/posix_object.cpp -o $(OBJDIR_DEBUG)/src/posix_object.o

$(OBJDIR_DEBUG)/src/posix_semaphore.o: src/posix_semaphore.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/posix_semaphore.cpp -o $(OBJDIR_DEBUG)/src/posix_semaphore.o

$(OBJDIR_DEBUG)/src/result.o: src/result.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/result.cpp -o $(OBJDIR_DEBUG)/src/result.o

$(OBJDIR_DEBUG)/src/shared_memory.o: src/shared_memory.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/shared_memory.cpp -o $(OBJDIR_DEBUG)/src/shared_memory.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) -shared $(LIBDIR_RELEASE) $(OBJ_RELEASE)  -o $(OUT_RELEASE) $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/msg_queue.o: src/msg_queue.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/msg_queue.cpp -o $(OBJDIR_RELEASE)/src/msg_queue.o

$(OBJDIR_RELEASE)/src/posix_object.o: src/posix_object.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/posix_object.cpp -o $(OBJDIR_RELEASE)/src/posix_object.o

$(OBJDIR_RELEASE)/src/posix_semaphore.o: src/posix_semaphore.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/posix_semaphore.cpp -o $(OBJDIR_RELEASE)/src/posix_semaphore.o

$(OBJDIR_RELEASE)/src/result.o: src/result.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/result.cpp -o $(OBJDIR_RELEASE)/src/result.o

$(OBJDIR_RELEASE)/src/shared_memory.o: src/shared_memory.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/shared_memory.cpp -o $(OBJDIR_RELEASE)/src/shared_memory.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

